blank_issues_enabled: false
contact_links:
  - name: Discuss Emogg on the Discord server.
    url: https://discord.gg/t5ZqftXG4b
    about: Discuss bug reports, suggestions or other Emogg related stuff on our Discord server.
