blank_issues_enabled: true
contact_links:
  - name: Discuss Emogg on the Discord server.
    url: https://discord.gg/wpNTd9PjEa
    about: Discuss bug reports, suggestions or other Emogg related stuff on my Discord server.
