name: Feature Suggestion
description: Create a feature suggestion to help expand the features Emogg has to offer.
labels: [suggestion]
body:
  - type: markdown
    attributes:
      value: "## Welcome!"
  - type: markdown
    attributes:
      value: |
        Thanks for taking your time to create your feature suggestion! If you want to discuss your suggestion, join us on [Discord](https://debuggy.gay/discord).
        Make sure you are running the latest version of Emogg before making the suggestion.
  - type: textarea
    id: features
    attributes:
      label: List the features you want added to Emogg.
      description: 
      value: |
        New emojis for the Twemogg pack

  - type: textarea
    id: description
    attributes:
      label: Describe how your feature(s) will work if applicable.
      description: "Describe the suggestion as clearly as possible. More info means the suggestion is more likely to be accepted."
      value: |
        Twitter emoji recently had an update where new emojis were added

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: "Add any other context about the feature suggestion here."
